# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    CMHA,
    DFL,
    ELAN1,
    MCSTA,
    MCTA,
    MSTA,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    SPPFDLSKA,
    SPPFFCA,
    SPPFLSKA,
    SPPFSP,
    SPPFSPDC,
    A2C2f,
    AConv,
    ADown,
    AFPBlock,
    AGMBlock,
    Attention,
    BiFPNBlock,
    BiFPNLayer3,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fDWR,
    C2fMDKA,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    CIEPool,
    ContrastiveHead,
    DWRBottleneck,
    GEBlock,
    GhostBottleneck,
    GhostProjConv,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MaxSigmoidAttnBlock,
    MDKABottleneck,
    MDKAConv,
    P2P3Fuse,
    Proto,
    RawRefineFuse,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    SECBAMLite,
    SPPFFCARes,
    SPPFLSKARes,
    SPPFSPRes,
    TorchVision,
    WeightedFusion,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .fca import FCALayer, FCALayerResidual
from .head import (
    OBB,
    Classify,
    Detect,
    LRPCHead,
    Pose,
    RTDETRDecoder,
    Segment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    v10Detect,
)
from .hwd import ConvHWDDown, HaarTransform2D, HWDDown
from .lska import LSKA, DirectionalLSKA, LSKARes
from .replk_sppf import LargeKernelDW, RepLKBranch, SPPFRepLKFull, SPPFRepLKLite
from .strip_pool import StripPoolingAtrous, StripPoolingLite, StripPoolingLiteRes
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "CMHA",
    "DFL",
    "ELAN1",
    "LSKA",
    "MCSTA",
    "MCTA",
    "MLP",
    "MSTA",
    "OBB",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "SPPFDLSKA",
    "SPPFFCA",
    "SPPFLSKA",
    "SPPFSP",
    "SPPFSPDC",
    "A2C2f",
    "AConv",
    "ADown",
    "AFPBlock",
    "AGMBlock",
    "Attention",
    "BNContrastiveHead",
    "BiFPNBlock",
    "BiFPNLayer3",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAttn",
    "C2fCIB",
    "C2fDWR",
    "C2fMDKA",
    "C2fPSA",
    "C3Ghost",
    "C3k2",
    "C3x",
    "CBFuse",
    "CBLinear",
    "CIEPool",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvHWDDown",
    "ConvTranspose",
    "DWConv",
    "DWConvTranspose2d",
    "DWRBottleneck",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "DirectionalLSKA",
    "FCALayer",
    "FCALayerResidual",
    "Focus",
    "GEBlock",
    "GhostBottleneck",
    "GhostConv",
    "GhostProjConv",
    "HGBlock",
    "HGStem",
    "HWDDown",
    "HaarTransform2D",
    "ImagePoolingAttn",
    "Index",
    "LRPCHead",
    "LSKARes",
    "LargeKernelDW",
    "LayerNorm2d",
    "LightConv",
    "MDKABottleneck",
    "MDKAConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "P2P3Fuse",
    "Pose",
    "Proto",
    "RTDETRDecoder",
    "RawRefineFuse",
    "RepC3",
    "RepConv",
    "RepLKBranch",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "SECBAMLite",
    "SPPFFCARes",
    "SPPFLSKARes",
    "SPPFRepLKFull",
    "SPPFRepLKLite",
    "SPPFSPRes",
    "Segment",
    "SpatialAttention",
    "StripPoolingAtrous",
    "StripPoolingLite",
    "StripPoolingLiteRes",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WeightedFusion",
    "WeightedFusion",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
    "v10Detect",
)
